---
- name: "Get VPC ID"
  ec2_vpc_net_facts:
    region: "{{ alb.aws_region }}"
    filters:
      "tag:Name": "{{ alb.vpc_name }}"
  register: vpc_net_fact

- name: "Create Target Group"
  command: aws elbv2 create-target-group --name "{{ alb.tg_name }}" --protocol HTTP --port 80 --vpc-id "{{ vpc_net_fact.vpcs[0].id }}"
  register: tg_fact

